CREATE TABLE WA_USERS (
  ID            BIGINT PRIMARY KEY    AUTO_INCREMENT,
  EMAIL         VARCHAR(32),
  MOBILE        VARCHAR(32)  NOT NULL,
  PASSWORD_HASH VARCHAR(128) NOT NULL,
  STATUS        INT          NOT NULL DEFAULT 0,
  CREATE_TIME   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_WA_USERS_EMAIL ON WA_USERS (EMAIL);
CREATE UNIQUE INDEX UQ_WA_USERS_MOBILE ON WA_USERS (MOBILE);
CREATE INDEX IX_WA_USERS_STATUS ON WA_USERS (STATUS);

CREATE TABLE WA_ROLES (
  UID       BIGINT PRIMARY KEY, -- relates to WA_USERS.ID
  AUTHORITY VARCHAR(32) NOT NULL
);

CREATE TABLE WA_CAPTCHA (
  CHALLENGE    VARCHAR(64) PRIMARY KEY,
  STORAGE_NAME VARCHAR(128) NOT NULL,
  CREATE_TIME  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_WA_CAPTCHA_CREATE_TIME ON WA_CAPTCHA (CREATE_TIME);
